language: node_js
node_js:
  - "9"
  - "10"
  - "11"
cache:
  directories:
    - "node_modules"
addons:
  code_climate:
    repo_token: b3658fd0ee9f4a540c536bf6b43b81ac3794b85fbc991abca086a90296f7b381

before_install:
  - npm i -g npm@latest
  - npm install --no-save @rxstack/core@^0.1 @rxstack/data-fixtures@^0.1 @rxstack/platform@^0.1 @rxstack/security@^0.1
install:
  - npm install
script:
  - npm test
after_script:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < ./coverage/lcov.info

services:
  - mongodb