version: '3'

services:
    app:
        build:
            context: ./app
        volumes:
            - ../:/var/www/application
        links:
            - mongo
    mongo:
        image: mongo
        ports:
            - 27017:27017


